server:
  port: 8080

spring:
  application:
    name: notification-service

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

  mail:
    host: ${SMTP_HOST:mailhog}
    port: ${SMTP_PORT:1025}
    username: ${SMTP_USER:}
    password: ${SMTP_PASS:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  amqp:
    deserialization:
      trust:
        all: true

notification:
  exchange: ${NOTIFICATION_EXCHANGE:notification.exchange}
  queue: ${NOTIFICATION_QUEUE:notification.queue}
  routingKey: ${NOTIFICATION_ROUTINGKEY:notification.key}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
